const widgets = [
  {
    name: 'PomodoroItem',
    x: 0,
    y: 0,
    w: 3,
    h: 5.5,
    i: '0',
    resizable: false,
    draggable: true,
    static: false,
    minW: 3,
    minH: 5.5,
    responsive: true,
  },
  {
    name: 'TimeSelector',
    x: 3,
    y: 0,
    w: 2,
    h: 5.5,
    i: '1',
    resizable: false,
    draggable: true,
    static: false,
    responsive: true,
  },
  {
    name: 'UserTodo',
    x: 5,
    y: 0,
    w: 3,
    h: 8,
    i: '2',
    resizable: false,
    draggable: true,
    static: false,
    responsive: true,
  },
  {
    name: 'StartTodo',
    x: 8,
    y: 0,
    w: 3,
    h: 9,
    i: '3',
    resizable: false,
    draggable: true,
    static: false,
    responsive: true,
  },
  {
    name: 'MusicPlayer',
    x: 0,
    y: 6,
    w: 2,
    h: 4,
    i: '4',
    resizable: false,
    draggable: true,
    static: false,
    dragIgnoreFrom: '.audio__player-progress-point, .audio__player-progress-container, audio',
    responsive: true,
  },
  {
    name: 'UserNote',
    x: 2,
    y: 6,
    w: 3,
    h: 3.5,
    i: '5',
    resizable: false,
    draggable: true,
    static: false,
    responsive: true,
    dragIgnoreFrom: '.q-editor__content',

  },
  {
    name: 'KanbanTable',
    x: 0,
    y: 0,
    w: 8,
    h: 8,
    i: '6',
    resizable: false,
    draggable: true,
    static: false,
    dragIgnoreFrom: 'VueDraggable, .draggable, input',
    responsive: true,
  }
];

export default widgets;
