
export const startersTask: {[lang: string] : string[]} = {
  "de": [
    "Alles bereit? Los geht's! 🚀",
    'Prüfung: Fühlst du dich wohl? 💺',
    'Prüfung: Hast du keinen Hunger? 🥙',
    'Prüfung: Hast du keinen Durst? 🧃',
    'Prüfung: Musst du auf die Toilette? 🚾',
    'Räume deinen Schreibtisch und dein Zimmer ein wenig auf 🧹',
    'Hast du alles, was du zum Arbeiten brauchst? 📓',
    'Verstecke alles, was dich ablenken könnte 😫',
    'Verstecke dein Handy, um Ablenkungen zu vermeiden (z. B. in der Schublade) 📵',
    'Bereite einen Plan für heute vor - was möchtest du heute tun? 📝',
    'Bereite einige Getränke vor ☕',
    'Bereite etwas zu essen vor 🥐',
    'Bereite deine Lieblingsmusik vor, wenn du möchtest 🎵',
    'Stelle deinen Pomodoro 🍅 ein',
    'Schalte das WLAN auf deinem Handy aus 📵',
  ],
  "pl": [
    'Wszystko gotowe? Zaczynajmy! 🚀',
    'Sprawdź: Czy czujesz się komfortowo? 💺',
    'Sprawdź: Czy nie jesteś głodny? 🥙',
    'Sprawdź: Czy nie jesteś spragniony? 🧃',
    'Sprawdź: Czy musisz iść do toalety? 🚾',
    'Posprzątaj trochę swoje biurko i pokój 🧹',
    'Masz wszystko, czego potrzebujesz do pracy? 📓',
    'Schowaj wszystko, co może cię rozpraszać 😫',
    'Schowaj telefon, aby uniknąć rozproszeń (np. do szuflady) 📵',
    'Przygotuj plan na dzisiaj - co chcesz dzisiaj zrobić? 📝',
    'Przygotuj napoje ☕',
    'Przygotuj jakieś przekąski 🥐',
    'Przygotuj swoją ulubioną muzykę, jeśli chcesz 🎵',
    'Ustaw swój pomodoro 🍅',
    'Wyłącz Wi-Fi w telefonie 📵',
  ],
  "ua": [
    'Все готово? Починаймо! 🚀',
    'Перевірка: Чи комфортно тобі? 💺',
    'Перевірка: Ти не голодний? 🥙',
    'Перевірка: Ти не хочеш пити? 🧃',
    'Перевірка: Тобі не треба в туалет? 🚾',
    'Прибери трохи на столі та в кімнаті 🧹',
    'Чи є все, що потрібно для роботи? 📓',
    'Сховай усе, що може тебе відволікати 😫',
    'Сховай телефон, щоб уникнути відволікань (наприклад, в ящик) 📵',
    'Підготуй план на сьогодні - що хочеш зробити сьогодні? 📝',
    'Приготуйте напої ☕',
    'Приготуйте перекуси 🥐',
    'Приготуйте свою улюблену музику, якщо хочеш 🎵',
    'Встановіть свій помодоро 🍅',
    'Вимкніть Wi-Fi на своєму телефоні 📵',
  ],
  "en-US": [
    'All set? Go! 🚀',
    'Check: Are you feeling comfortable? 💺',
    'Check: Are you not hungry? 🥙',
    'Check: Are you not thirsty? 🧃',
    'Check: Need to go to the bathroom? 🚾',
    'Clean your desk and room a bit 🧹',
    'Do you have everything you need to work? 📓',
    'Hide everything what can distract you 😫',
    'Hide phone to avoid distractions (to the drawer, for example) 📵',
    'Prepare a plan for today - what you want to do today? 📝',
    'Prepare some drinks ☕',
    'Prepare some snacks 🥐',
    'Prepare your favorite music if you want 🎵',
    'Set your pomodoro 🍅',
    'Turn off wi-fi on your phone 📵',
  ],
};
